sudo: required

services:
  - docker

script:
 - docker pull dxjoke/tectonic-docker
 - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic --keep-intermediates --reruns 0 bachproef\bachproef-tin.tex; biber bachproef\bachproef-tin; tectonic bachproef\bachproef-tin.tex"